title: avdw.dev
email: info@avdw.dev
author: Abe van der Wielen
description: >-
    Personal site of Abe van der Wielen.
    Follow for developer related thoughts, ideas, explanations and code snippets.
baseurl: ""
url: "https://avdw.dev"
twitter_username: abevdw
github_username: the-abe
encoding: utf-8
show_excerpts: true
paginate: 5
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
